Improve make checks
These improvements are back-ported from the approved pull requests:

 * https://github.com/terraform-google-modules/terraform-google-startup-scripts/pull/5
 * https://github.com/terraform-google-modules/terraform-google-startup-scripts/pull/6

Without this patch there are a number of annoyances with the make
checks.  This patch fixes the following:

 1. Checks execute against .git/ and .terraform/ directories
 2. terraform validate executes redundantly

The patch refactors make.sh to use a general find | xargs pattern with a
single function to manage exclusion lists.

check_shebangs is removed because `#! /bin/bash -e` should not be used
because it does not take effect if the script is called via bash
<filename>.  Instead, calling `set -e` is preferred.

Add .terraform to the make check exclusion list

Use find_files to gain exclusion with check_headers

Without this patch the check_headers task descends into .terraform and
.git directories which causes false positive errors.

This patch switches check_headers to the find_files method, which has a
shared exclusion list containing .git and .terraform.

Fix combine_docfiles.py W605 and newline error

This patch fixes three issues with the make generate_docs task:

 1. Directories with *.tf files and no README.md throw errors.
 2. Newline at EOF is stripped from README.md
 3. W605 pylint warnings on combine_docfiles.py

Change-Id: I31604bb50113afc9ed3c1db7d318340636761040

Fix `terraform validate` errors with newly created module

Without this patch a new module fails with the following error:

    Running terraform validate
    Error: output 'project_id': unknown variable referenced: 'project_id'; define it with a 'variable' block
    Error: output 'bucket_name': unknown module referenced: example
    make: *** [check_terraform] Error 1

This directory is not a complete module and therefor won't pass
validation checks.  The code itself is still validated when symlinked
into a complete module, e.g. ./test/fixtures/simple_example/outputs.tf
-> ../shared/outputs.tf

Fix grep file not found error

Without this patch grep fails when it encounters the dangling symlink
created initially when invoking cookiecutter.